# Site settings
title: weekof.denverdevs.org – Denver, June 2017
description: "weekof.denverdevs.org is a collection of fine events around the web, happening in Denver in June 2017"
baseurl: ""
url: "http://weekof.denverdevs.org"
exclude:
  - README.md

# Build settings
markdown: kramdown
permalink: pretty

# Site data
github_repo: "denver-devs/weekof.denverdevs.org"
twitter_username: denverdevs
